// Generated by scripts/generate-pixel-assets.mjs. Do not edit by hand.
export type GeneratedAssetCategory = "environments" | "props" | "characters" | "ui" | "icons" | "effects";

export type GeneratedAsset = {
  key: string;
  name: string;
  role: string;
  path: string;
  uiPath: string;
};

export const generatedAssets = {
  environments: [
    { key: "gen-environment-bunker-cross-section", name: "bunker-cross-section", role: "2.5D side-view shelter background", path: "assets/generated/environments/bunker-cross-section.svg", uiPath: "/assets/generated/environments/bunker-cross-section.svg" },
    { key: "gen-environment-red-sand-skyline", name: "red-sand-skyline", role: "external red sand wasteland skyline", path: "assets/generated/environments/red-sand-skyline.svg", uiPath: "/assets/generated/environments/red-sand-skyline.svg" },
    { key: "gen-environment-broken-wall-module", name: "broken-wall-module", role: "damaged shelter wall module", path: "assets/generated/environments/broken-wall-module.svg", uiPath: "/assets/generated/environments/broken-wall-module.svg" },
    { key: "gen-environment-metal-floor-tiles", name: "metal-floor-tiles", role: "rusted metal floor strip", path: "assets/generated/environments/metal-floor-tiles.svg", uiPath: "/assets/generated/environments/metal-floor-tiles.svg" },
    { key: "gen-environment-pipe-cable-bundle", name: "pipe-cable-bundle", role: "pipes and exposed cable bundle", path: "assets/generated/environments/pipe-cable-bundle.svg", uiPath: "/assets/generated/environments/pipe-cable-bundle.svg" },
    { key: "gen-environment-ventilation-room-module", name: "ventilation-room-module", role: "ventilation room structure", path: "assets/generated/environments/ventilation-room-module.svg", uiPath: "/assets/generated/environments/ventilation-room-module.svg" },
    { key: "gen-environment-security-door-module", name: "security-door-module", role: "security door zone structure", path: "assets/generated/environments/security-door-module.svg", uiPath: "/assets/generated/environments/security-door-module.svg" },
    { key: "gen-environment-communication-room-module", name: "communication-room-module", role: "radio desk zone structure", path: "assets/generated/environments/communication-room-module.svg", uiPath: "/assets/generated/environments/communication-room-module.svg" },
    { key: "gen-environment-medical-room-module", name: "medical-room-module", role: "medical corner structure", path: "assets/generated/environments/medical-room-module.svg", uiPath: "/assets/generated/environments/medical-room-module.svg" },
    { key: "gen-environment-water-room-module", name: "water-room-module", role: "water treatment zone structure", path: "assets/generated/environments/water-room-module.svg", uiPath: "/assets/generated/environments/water-room-module.svg" },
    { key: "gen-environment-task-wall-module", name: "task-wall-module", role: "whiteboard and task wall structure", path: "assets/generated/environments/task-wall-module.svg", uiPath: "/assets/generated/environments/task-wall-module.svg" },
    { key: "gen-environment-rooftop-beacon-rig", name: "rooftop-beacon-rig", role: "rooftop beacon environment rig", path: "assets/generated/environments/rooftop-beacon-rig.svg", uiPath: "/assets/generated/environments/rooftop-beacon-rig.svg" }
  ],
  props: [
    { key: "gen-prop-water-tank", name: "water-tank", role: "water storage tank", path: "assets/generated/props/water-tank.svg", uiPath: "/assets/generated/props/water-tank.svg" },
    { key: "gen-prop-filter-pump", name: "filter-pump", role: "filter pump", path: "assets/generated/props/filter-pump.svg", uiPath: "/assets/generated/props/filter-pump.svg" },
    { key: "gen-prop-medkit", name: "medkit", role: "medical kit", path: "assets/generated/props/medkit.svg", uiPath: "/assets/generated/props/medkit.svg" },
    { key: "gen-prop-medicine-crate", name: "medicine-crate", role: "medicine crate", path: "assets/generated/props/medicine-crate.svg", uiPath: "/assets/generated/props/medicine-crate.svg" },
    { key: "gen-prop-radio-terminal", name: "radio-terminal", role: "radio terminal", path: "assets/generated/props/radio-terminal.svg", uiPath: "/assets/generated/props/radio-terminal.svg" },
    { key: "gen-prop-small-console", name: "small-console", role: "small control console", path: "assets/generated/props/small-console.svg", uiPath: "/assets/generated/props/small-console.svg" },
    { key: "gen-prop-security-door", name: "security-door", role: "security door", path: "assets/generated/props/security-door.svg", uiPath: "/assets/generated/props/security-door.svg" },
    { key: "gen-prop-lock-panel", name: "lock-panel", role: "lock control panel", path: "assets/generated/props/lock-panel.svg", uiPath: "/assets/generated/props/lock-panel.svg" },
    { key: "gen-prop-warning-light", name: "warning-light", role: "warning light", path: "assets/generated/props/warning-light.svg", uiPath: "/assets/generated/props/warning-light.svg" },
    { key: "gen-prop-vent-fan", name: "vent-fan", role: "vent fan", path: "assets/generated/props/vent-fan.svg", uiPath: "/assets/generated/props/vent-fan.svg" },
    { key: "gen-prop-generator", name: "generator", role: "generator", path: "assets/generated/props/generator.svg", uiPath: "/assets/generated/props/generator.svg" },
    { key: "gen-prop-battery-box", name: "battery-box", role: "battery box", path: "assets/generated/props/battery-box.svg", uiPath: "/assets/generated/props/battery-box.svg" },
    { key: "gen-prop-file-crate", name: "file-crate", role: "resident file crate", path: "assets/generated/props/file-crate.svg", uiPath: "/assets/generated/props/file-crate.svg" },
    { key: "gen-prop-task-sticky-notes", name: "task-sticky-notes", role: "whiteboard sticky notes", path: "assets/generated/props/task-sticky-notes.svg", uiPath: "/assets/generated/props/task-sticky-notes.svg" },
    { key: "gen-prop-toolbox", name: "toolbox", role: "toolbox", path: "assets/generated/props/toolbox.svg", uiPath: "/assets/generated/props/toolbox.svg" },
    { key: "gen-prop-repair-parts", name: "repair-parts", role: "repair parts", path: "assets/generated/props/repair-parts.svg", uiPath: "/assets/generated/props/repair-parts.svg" },
    { key: "gen-prop-scrap-electronics", name: "scrap-electronics", role: "scrap electronics", path: "assets/generated/props/scrap-electronics.svg", uiPath: "/assets/generated/props/scrap-electronics.svg" }
  ],
  characters: [
    { key: "gen-character-aura-agent", name: "aura-agent", role: "AURA pixel drone body", path: "assets/generated/characters/aura-agent.svg", uiPath: "/assets/generated/characters/aura-agent.svg" },
    { key: "gen-character-resident-technician", name: "resident-technician", role: "resident technician", path: "assets/generated/characters/resident-technician.svg", uiPath: "/assets/generated/characters/resident-technician.svg" },
    { key: "gen-character-resident-medic", name: "resident-medic", role: "resident medic", path: "assets/generated/characters/resident-medic.svg", uiPath: "/assets/generated/characters/resident-medic.svg" },
    { key: "gen-character-resident-security", name: "resident-security", role: "resident security guard", path: "assets/generated/characters/resident-security.svg", uiPath: "/assets/generated/characters/resident-security.svg" },
    { key: "gen-character-resident-injured", name: "resident-injured", role: "injured resident", path: "assets/generated/characters/resident-injured.svg", uiPath: "/assets/generated/characters/resident-injured.svg" },
    { key: "gen-character-resident-civilian", name: "resident-civilian", role: "civilian resident", path: "assets/generated/characters/resident-civilian.svg", uiPath: "/assets/generated/characters/resident-civilian.svg" }
  ],
  ui: [
    { key: "gen-u-pixel-button", name: "pixel-button", role: "pixel style button plate", path: "assets/generated/ui/pixel-button.svg", uiPath: "/assets/generated/ui/pixel-button.svg" },
    { key: "gen-u-panel-frame", name: "panel-frame", role: "rusted pixel panel frame", path: "assets/generated/ui/panel-frame.svg", uiPath: "/assets/generated/ui/panel-frame.svg" },
    { key: "gen-u-hud-card", name: "hud-card", role: "HUD card plate", path: "assets/generated/ui/hud-card.svg", uiPath: "/assets/generated/ui/hud-card.svg" },
    { key: "gen-u-console-frame", name: "console-frame", role: "agent console frame", path: "assets/generated/ui/console-frame.svg", uiPath: "/assets/generated/ui/console-frame.svg" },
    { key: "gen-u-timeline-node", name: "timeline-node", role: "day timeline node", path: "assets/generated/ui/timeline-node.svg", uiPath: "/assets/generated/ui/timeline-node.svg" },
    { key: "gen-u-replay-feed-icon", name: "replay-feed-icon", role: "replay feed chip", path: "assets/generated/ui/replay-feed-icon.svg", uiPath: "/assets/generated/ui/replay-feed-icon.svg" },
    { key: "gen-u-ending-rescue-card", name: "ending-rescue-card", role: "rescue ending card plate", path: "assets/generated/ui/ending-rescue-card.svg", uiPath: "/assets/generated/ui/ending-rescue-card.svg" },
    { key: "gen-u-ending-lighthouse-card", name: "ending-lighthouse-card", role: "lighthouse ending card plate", path: "assets/generated/ui/ending-lighthouse-card.svg", uiPath: "/assets/generated/ui/ending-lighthouse-card.svg" }
  ],
  icons: [
    { key: "gen-icon-water", name: "water", role: "water metric icon", path: "assets/generated/icons/water.svg", uiPath: "/assets/generated/icons/water.svg" },
    { key: "gen-icon-medicine", name: "medicine", role: "medicine metric icon", path: "assets/generated/icons/medicine.svg", uiPath: "/assets/generated/icons/medicine.svg" },
    { key: "gen-icon-safety", name: "safety", role: "safety metric icon", path: "assets/generated/icons/safety.svg", uiPath: "/assets/generated/icons/safety.svg" },
    { key: "gen-icon-signal", name: "signal", role: "signal metric icon", path: "assets/generated/icons/signal.svg", uiPath: "/assets/generated/icons/signal.svg" },
    { key: "gen-icon-morale", name: "morale", role: "morale metric icon", path: "assets/generated/icons/morale.svg", uiPath: "/assets/generated/icons/morale.svg" },
    { key: "gen-icon-trust", name: "trust", role: "trust metric icon", path: "assets/generated/icons/trust.svg", uiPath: "/assets/generated/icons/trust.svg" },
    { key: "gen-icon-resource", name: "resource", role: "resource task icon", path: "assets/generated/icons/resource.svg", uiPath: "/assets/generated/icons/resource.svg" },
    { key: "gen-icon-social", name: "social", role: "social task icon", path: "assets/generated/icons/social.svg", uiPath: "/assets/generated/icons/social.svg" },
    { key: "gen-icon-creative", name: "creative", role: "creative task icon", path: "assets/generated/icons/creative.svg", uiPath: "/assets/generated/icons/creative.svg" },
    { key: "gen-icon-retrieval", name: "retrieval", role: "retrieval task icon", path: "assets/generated/icons/retrieval.svg", uiPath: "/assets/generated/icons/retrieval.svg" },
    { key: "gen-icon-classification", name: "classification", role: "classification task icon", path: "assets/generated/icons/classification.svg", uiPath: "/assets/generated/icons/classification.svg" },
    { key: "gen-icon-puzzle", name: "puzzle", role: "puzzle task icon", path: "assets/generated/icons/puzzle.svg", uiPath: "/assets/generated/icons/puzzle.svg" },
    { key: "gen-icon-planning", name: "planning", role: "planning task icon", path: "assets/generated/icons/planning.svg", uiPath: "/assets/generated/icons/planning.svg" }
  ],
  effects: [
    { key: "gen-effect-success-pulse", name: "success-pulse", role: "success pulse effect", path: "assets/generated/effects/success-pulse.svg", uiPath: "/assets/generated/effects/success-pulse.svg" },
    { key: "gen-effect-failure-alarm", name: "failure-alarm", role: "failure alarm effect", path: "assets/generated/effects/failure-alarm.svg", uiPath: "/assets/generated/effects/failure-alarm.svg" },
    { key: "gen-effect-highlight-border", name: "highlight-border", role: "zone highlight border", path: "assets/generated/effects/highlight-border.svg", uiPath: "/assets/generated/effects/highlight-border.svg" },
    { key: "gen-effect-scan-ring", name: "scan-ring", role: "AURA scan ring", path: "assets/generated/effects/scan-ring.svg", uiPath: "/assets/generated/effects/scan-ring.svg" },
    { key: "gen-effect-task-progress", name: "task-progress", role: "task execution progress bar", path: "assets/generated/effects/task-progress.svg", uiPath: "/assets/generated/effects/task-progress.svg" },
    { key: "gen-effect-path-highlight", name: "path-highlight", role: "movement path highlight", path: "assets/generated/effects/path-highlight.svg", uiPath: "/assets/generated/effects/path-highlight.svg" },
    { key: "gen-effect-beacon-flash", name: "beacon-flash", role: "beacon flash effect", path: "assets/generated/effects/beacon-flash.svg", uiPath: "/assets/generated/effects/beacon-flash.svg" }
  ]
} as const satisfies Record<GeneratedAssetCategory, readonly GeneratedAsset[]>;

export const phaserGeneratedAssets: readonly GeneratedAsset[] = Object.values(generatedAssets).flat();

export const generatedAssetByName = Object.fromEntries(
  phaserGeneratedAssets.map((asset) => [asset.name, asset])
) as Record<string, GeneratedAsset>;

export const metricIconAssets = {
  water: generatedAssetByName.water.uiPath,
  medicine: generatedAssetByName.medicine.uiPath,
  trust: generatedAssetByName.trust.uiPath,
  safety: generatedAssetByName.safety.uiPath,
  signal: generatedAssetByName.signal.uiPath,
  morale: generatedAssetByName.morale.uiPath
} as const;

export const taskCategoryIconAssets = {
  resource: generatedAssetByName.resource.uiPath,
  social: generatedAssetByName.social.uiPath,
  creative: generatedAssetByName.creative.uiPath,
  retrieval: generatedAssetByName.retrieval.uiPath,
  classification: generatedAssetByName.classification.uiPath,
  puzzle: generatedAssetByName.puzzle.uiPath,
  planning: generatedAssetByName.planning.uiPath,
  safety: generatedAssetByName.safety.uiPath,
  vision: generatedAssetByName.safety.uiPath
} as const;
